apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nginxhello-blue
spec:
  minReplicas: 2  # define min replica count
  maxReplicas: 10 # define max replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginxhello-blue
  targetCPUUtilizationPercentage: 20 # target CPU utilization