apiVersion: v1
kind: Service
metadata:
  name: docker-python-svc
  labels:  
    app: docker-python
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-python