name: Deploy AKS resources
on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy-RG
      run: az deployment sub create --location ${{ vars.LOCATION }} --template-file bicep/resourcegroup.bicep --param location=${{ vars.LOCATION }} --query "{suffix:properties.outputs.suffix.value, resourceGroupName:properties.outputs.resourceGroupName.value}" --output tsv > outputs.txt

    - name: Set environment variables
      run: |
        echo "SUFFIX=$(cat outputs.txt | awk '{print $1}')" >> $GITHUB_ENV
        echo "RG_NAME=$(cat outputs.txt | awk '{print $2}')" >> $GITHUB_ENV

    - name: Use environment variables
      run: |
        echo "Resource Group Name: $RG_NAME"
        echo "Suffix: $SUFFIX"

    - name: Deploy-RG
      run: az deployment group create --resource-group $RG_NAME --template-file bicep/main.bicep --parameters location=${{ vars.LOCATION }} suffix=$SUFFIX
