name: Deploy Bicep files
on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy-RG
      run: az deployment sub create --location ${{ vars.LOCATION }} \
        --template-file bicep/resourcegroup.bicep \
        --param location=${{ vars.LOCATION }} \
        --output tsv > outputs.txt

    - name: Set environment variable
      run: cat outputs.txt


    #- name: Print Deployment Outputs
      #run: |
        #echo "intOutput: ${{ steps.deployment.outputs.intOutput }}"
        #echo "stringOutput: ${{ steps.deployment.outputs.stringOutput }}"
