name: Deploy Bicep files
on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy-RG
      run: az deployment sub create --location eastus2 --template-file bicep/resourcegroup.bicep --param location=eastus2 --query "{suffix:properties.outputs.suffix.value, resourceGroupName:properties.outputs.resourceGroupName.value}" --output tsv > outputs.txt

    - name: Set environment variable
      run: cat outputs.txt

    - name: Set environment variables
      run: |
        echo "SUFFIX=$(cat outputs.txt | awk '{print $1}')" >> $GITHUB_ENV
        echo "RG_NAME=$(cat outputs.txt | awk '{print $2}')" >> $GITHUB_ENV

    - name: Use environment variables
      run: |
        echo "Resource Group Name: $RG_NAME"
        echo "Suffix: $SUFFIX"


    #- name: Print Deployment Outputs
      #run: |
        #echo "intOutput: ${{ steps.deployment.outputs.intOutput }}"
        #echo "stringOutput: ${{ steps.deployment.outputs.stringOutput }}"
